import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
// ↑ Global stylesheet applied to the entire React application.

import App from './App';
// ↑ Root component containing all UI + functionality.

import reportWebVitals from './reportWebVitals';
// ↑ Optional performance measurement tool generated by Create React App.


const root = ReactDOM.createRoot(document.getElementById('root'));
// ↑ Find the <div id="root"></div> in index.html and attach React to it.
//   `createRoot` is the React 18 API for concurrent rendering.

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
// ↑ Render the <App /> component inside React Strict Mode.
//   StrictMode helps catch issues and warns about deprecated patterns,
//   but does not affect the production build.

reportWebVitals();
// ↑ This calls the optional performance logging. Currently does nothing.
//   You can ignore or remove this if not needed.
